/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThankyouIndexRouteImport } from './routes/thankyou/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as TransactionTidRouteImport } from './routes/transaction/$tid'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as CheckoutTidRouteImport } from './routes/checkout/$tid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankyouIndexRoute = ThankyouIndexRouteImport.update({
  id: '/thankyou/',
  path: '/thankyou/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionTidRoute = TransactionTidRouteImport.update({
  id: '/transaction/$tid',
  path: '/transaction/$tid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTidRoute = CheckoutTidRouteImport.update({
  id: '/checkout/$tid',
  path: '/checkout/$tid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout/$tid': typeof CheckoutTidRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/transaction/$tid': typeof TransactionTidRoute
  '/cart/': typeof CartIndexRoute
  '/error/': typeof ErrorIndexRoute
  '/login/': typeof LoginIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/thankyou/': typeof ThankyouIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/$tid': typeof CheckoutTidRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/transaction/$tid': typeof TransactionTidRoute
  '/cart': typeof CartIndexRoute
  '/error': typeof ErrorIndexRoute
  '/login': typeof LoginIndexRoute
  '/products': typeof ProductsIndexRoute
  '/thankyou': typeof ThankyouIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout/$tid': typeof CheckoutTidRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/transaction/$tid': typeof TransactionTidRoute
  '/cart/': typeof CartIndexRoute
  '/error/': typeof ErrorIndexRoute
  '/login/': typeof LoginIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/thankyou/': typeof ThankyouIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout/$tid'
    | '/product/$productId'
    | '/transaction/$tid'
    | '/cart/'
    | '/error/'
    | '/login/'
    | '/products/'
    | '/thankyou/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout/$tid'
    | '/product/$productId'
    | '/transaction/$tid'
    | '/cart'
    | '/error'
    | '/login'
    | '/products'
    | '/thankyou'
  id:
    | '__root__'
    | '/'
    | '/checkout/$tid'
    | '/product/$productId'
    | '/transaction/$tid'
    | '/cart/'
    | '/error/'
    | '/login/'
    | '/products/'
    | '/thankyou/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutTidRoute: typeof CheckoutTidRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  TransactionTidRoute: typeof TransactionTidRoute
  CartIndexRoute: typeof CartIndexRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ThankyouIndexRoute: typeof ThankyouIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thankyou/': {
      id: '/thankyou/'
      path: '/thankyou'
      fullPath: '/thankyou/'
      preLoaderRoute: typeof ThankyouIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error/'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/$tid': {
      id: '/transaction/$tid'
      path: '/transaction/$tid'
      fullPath: '/transaction/$tid'
      preLoaderRoute: typeof TransactionTidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$tid': {
      id: '/checkout/$tid'
      path: '/checkout/$tid'
      fullPath: '/checkout/$tid'
      preLoaderRoute: typeof CheckoutTidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutTidRoute: CheckoutTidRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  TransactionTidRoute: TransactionTidRoute,
  CartIndexRoute: CartIndexRoute,
  ErrorIndexRoute: ErrorIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ThankyouIndexRoute: ThankyouIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
